# Stop callmedia desktop Service
- hosts: all
  tasks:
  - name: check "callmedia desktop" service exists
    win_command: taskkill /IM "cmDesktop.exe" /F
    register: callmedia desktop_status

  - name: debug
    debug:
    var: "callmedia desktop_status"
       
#  - name: Stop and disable desktop service
#    debug:
#       msg: "status in w32time_status"
#    win_service:
#      name: "callmedia desktop"
#      state: stopped
#      start_mode: auto
# when: callmedia desktop_status.stdout | search("Status")

# Taking Backup of exiting callmedia desktop folder
- hosts: all
  tasks:
  - name: Copy a single file
    win_shell: echo %HOMEDIR%
    args:
      executable: cmd
    register: homedir_out

  - name: Backup of exiting callmedia Desktop folder
    win_copy:
      src: C:\Program Files (x86)\Callmedia\Callmedia Desktop
      dest: C:\CM-desktop-bck
      remote_src: yes

# copy code zip on local
#---
- hosts: localhost
  tasks:
  - name: Ansible zip file with path example
    archive:
      path: "/root/myagent/_work/r2/a/_Callmedia Desktop"
      dest: /tmp/ansible-demo/CMDesktop.zip
      format: zip

# copy code zip to remote machine
- hosts: all
  gather_facts: no
  tasks:
  - name: Copy the code
    win_copy:
      src: "/tmp/ansible-demo/CMDesktop.zip"
      dest: C:\\CM-enterprise-bck\\

  - name: Extract code
    win_unzip:
      src: C:\\CM-enterprise-bck\\CMDesktop.zip
      dest: C:\\Program Files (x86)\\Callmedia\\Callmedia Desktop\\

# Start callmedia enterprise Service
- hosts: all
  tasks:
  - name: check "Callmedia Desktop" service running
    #win_command: Start-Process -FilePath C:\Users\parag\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Callmedia Expert Contact\Desktop.lnk
    win_command:  powershell.exe -windowstyle hidden -file C:\start-desktop-CMD.ps1

#    register: callmedia enterprise_status

#  - name: debug
#    debug:
#       var: "callmedia desktop_status"

#  - name: Stop and disable enterprise service
#    debug:
#       msg: "status in w32time_status"
#    win_service:
#      name: "Callmedia Desktop"
#      state: started
#      start_mode: auto
#   when: Callmedia Desktop_status.stdout | search("Status")
